### ISSUE TITLE
[META] still need to support node 6?

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1033]
@blakeembrey 

I'm not opposed to supporting node 6 and/or 8, but I also don't know the history, if any.  Did you hear from a bunch of users who were stuck on node 6?  I assume that when you initially set up CI tests, node 6 was relevant, and the tests haven't been updated since then.

Node 8 was EOLd in December.  If we wanted to make our lives a little easier, we could start supporting node >=10.

**Comment by blakeembrey** [comment]
> I assume that when you initially set up CI tests, node 6 was relevant, and the tests haven't been updated since then.

Basically this, and bumping it is a major breaking change (as discovered when we accidentally updated `yn`). We should bump it in the next major version, which can honestly be whenever - just haven't had any breaking change needs yet since I haven't been actively building new features. Feel free to bump whenever you want.

**Comment by cspotcode** [comment]
Ok, sounds good.  Are you ok bumping up to node 10?

**Comment by cspotcode** [comment]
Bumped by #1036 which can be merged whenever we make the next major release.
