### ISSUE TITLE
Should I use it in production?

### ISSUE THREAD

**Issue by aayushkapoor206** [TypeStrong/ts-node#104]
I couldn't find any mention about it in the readme

**Comment by blakeembrey** [comment]
No, not really. In production you'd want to **only** be in transpile mode (you should have already type checked). If someone wants to contribute some PRs for this functionality, we can get it in. Otherwise I'd wait for #44.

**Comment by prashaantt** [comment]
So @blakeembrey, can we *now* use it in production? As in

```shell
$ ts-node -F server.ts
```

I currently do `tsc && node build/server.js`, but the very succinctness and beauty of the above is totally worth it if I'll get no significant overheads over the second option.

**Comment by blakeembrey** [comment]
Definitely your choice, go ahead 😄 There's no heavy overheads.

**Comment by Diluka** [comment]
using `ts-node -F .` to run ts code missing metadata. `reflect-metadata` can't get field's type.

`tsc && node .` is OK

**Comment by blakeembrey** [comment]
That make sense to me. Fast mode isn’t using type information, it’s just plain transpiling files on the fly. That’s not equivalent to `tsc`. Use the regular mode that is if you want type information. It’s a good point though and I can document that.

**Comment by Diluka** [comment]
So, should I use in production?
`ts-node .` or `tsc && node .`

**Comment by blakeembrey** [comment]
That's not something I can tell you. I can tell you that loading type information has a larger overhead, but it shouldn't impact performance (only memory once started).

**Comment by IAMtheIAM** [comment]
Hey, FYI there still no documentation mention about the `--fast` or `-F` option. I just found it here. That's something worth adding to the readme along with a basic intro about what it does, if its still a valid option.

**Comment by blakeembrey** [comment]
It's the default behaviour. See https://github.com/TypeStrong/ts-node/releases/tag/v4.0.0.

**Comment by leotm** [comment]
The release note mentions *use --type-check for type checking behaviour*, but its not mentioned again in the [docs](https://github.com/TypeStrong/ts-node#user-content-cli-and-programmatic-options)?

**Comment by blakeembrey** [comment]
That’s because it was three major releases ago and the behaviour was reverted. It confused other people to not type check by default.

**Comment by franklinyu** [comment]
So the `--transpileOnly` works similar to previous `--fast`?

**Comment by blakeembrey** [comment]
The same, yes.

**Comment by Rakhmanov** [comment]
> So the `--transpileOnly` works similar to previous `--fast`?

Except its `--transpile-only` or `-T`

**Comment by isaadabbasi** [comment]
So, the summary of this thread is that "If i use ts-node server.ts in production, that is completely okay, as it is transpile only mode by default so dont need to pass --fast or --transpile-only flags.

correct me if something is missed.

**Comment by mtrenker** [comment]
> So, the summary of this thread is that "If i use ts-node server.ts in production, that is completely okay, as it is transpile only mode by default so dont need to pass --fast or --transpile-only flags.
> 
> correct me if something is missed.

https://github.com/TypeStrong/ts-node#cli-and-programmatic-options says `--transpileOnly` is `false` by default.

**Comment by blakeembrey** [comment]
That’s correct. There was a period of time it was the default for performance reasons, but I received a lot of issues because it differed from typescript. You’ll need the flag or use the register file for it.

**Comment by lukewlms** [comment]
So the *new* summary of this thread is:

_Go ahead and use ts-node in production; just set the `--transpile-only` flag._

Is that correct?

**Comment by flux627** [comment]
A user early in this thread said that `reflect-metadata` broke when using this in `-T` (at the time it was `-F`) mode. Is this still the case?

**Comment by blakeembrey** [comment]
Yes, it’s not possible to get type information if your compiling without type information - which is what transpile only does.

**Comment by schmod** [comment]
I haven't seen any issues with sequelize-typescript – the current limitation may be _specifically_ limited to the enum issue described in #873.

**Comment by iiian** [comment]
General query to this thread: Out of curiosity, _what are the arguments for not using_ `ts-node` _in production_ ? Is there a good, important reason?

**Comment by FranklinYu** [comment]
@iiian I don't think there is one, as long as you pass the correct flag disabling type checking. The one mentioned above may be outdated and I recommend you to check manual for the exact name.

**Comment by Hless** [comment]
@iiian The only one I can think of is resource limitation. The compile step does take up some resources. I bumped into this issue today where one of my containers wouldn't launch because it was sufficient memory to compile my app.

**Comment by rrrix** [comment]
Thumbs up if you're using `ts-node` in Production 😁  

I am! 👍 

Sad face if you're too afraid 😢

**Comment by warent** [comment]
Thumbs up and sad face because going to production and afraid

**Comment by justinTime225** [comment]
> Thumbs up and sad face because going to production and afraid

Same!  Been migrating a node.js app to typescript.  I tried running "tsc && node dist/app.js" but kept getting `cannot find module` from a local ts file.  This is the only resort unfortunately, fingers crossed.

**Comment by cspotcode** [comment]
@bluematter you'll probably have better luck in the TypeScript Community Discord: https://discord.com/invite/typescript
It's very active, with plenty of people answering questions.  Be prepared to ask your question with sufficient detail, and you should get a good answer.

**Comment by divmgl** [comment]
> It seems that there is not much difference in speed but there is a difference in memory usage and "--transpile-only" doesn't change much about it

We actually just faced an outage because of this as the max size of the heap in Node.js by default is 512mb. We were getting very close it before, but we moved some packages around and `ts-node` managed to hit that limit. We didn't have `--transpile-only` set, so setting it did alleviate the issue, but the amount of memory being used is still absurdly close to the limit.

**Comment by cybercase** [comment]
@leventkaragol thanks for sharing your benchmark and results.
I've pasted your code into `src/index.ts` and ran it on my machine (m1 mac) with both node 18 (v18.17.1) and node 20 (v20.10.0) and I noticed some differences in the results:

**node 18**
- `node dist/index.js` => 4.92 MB and 16.321 seconds
- `npx ts-node src/index.ts` => 102.26 MB and 15.538 seconds
- `npx ts-node --transpile-only src/index.ts` => 31.21 MB and 15.547 seconds

**node 20**
- `node dist/index.js` => 3.37 MB and 16.284 seconds
- `npx ts-node src/index.ts` => 109.67 MB and 15.646 seconds
- `npx ts-node --transpile-only src/index.ts` => 23.77 MB and 15.529 seconds

Tests report the memory footprint is reduced significantly when using `--transpile-only` both on node 18 and node 20.

However, the most interesting result that tests report comes from Node20, when switching from CommonJS to ESM (by adding "type": "module" in `package.json`).

You'll have to ditch the `ts-node` executable and replace it with `node --loader ts-node/esm`  because of this https://github.com/TypeStrong/ts-node/issues/1997 , and cope with a [warning](https://stackoverflow.com/questions/63317051/node9511-experimentalwarning-the-esm-module-loader-is-experimental) that's there since node14 (but I think there's a newer flag or api to get rid of that)

**node 20 ESM**
- `node dist/index.js` => 3.92 MB and 16.569 seconds
- `node --loader ts-node/esm src/index.ts` => 3.63 MB and 16.46 seconds
- `node --loader ts-node/esm/transpile-only src/index.ts` => 3.62 MB and 16.599 seconds

So, for this last test, it looks like the memory usage is not affected at all by the `ts-node/esm` loader.

Hope this can be helpful to people researching on the same topic.
