### ISSUE TITLE
`ignored()` bug: ESM loader will try to compile .cjs, .mjs, and other unexpected file extensions

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1098]
ESM loader uses our current `ignored()` implementation to determine if it should transform a file.  This only excludes the .js and .jsx file extensions as needed.  This worked fine with our CommonJS loader, because we knew we were only registered for the .ts, .tsx, and maybe .js and .jsx extensions.

The ESM loader is different, so it's asking `ignore()` about .mjs files.  (maybe other extensions too?)

We need to update the `ignored()` implementation to include rather than exclude file extensions so that we only transform the same files that `tsc` can transform.

https://github.com/TypeStrong/ts-node/blob/ce7c323557c15bf878bbc4dd5b2c0aac219fca4b/src/index.ts#L837-L845

**Comment by concision** [comment]
Is it fine if I author a pull request for this?

I was thinking of reusing the conditions from the exported function [`getExtensions(config: _ts.ParsedCommandLine)`](https://github.com/TypeStrong/ts-node/blob/ce7c323557c15bf878bbc4dd5b2c0aac219fca4b/esm.mjs#L7):

```ts
  const ignored = (fileName: string) => {
    if (!active) return true
    const ext = extname(fileName)
    const extensions = getExtensions(config)
    if (extensions.tsExtensions.includes(ext) || extensions.jsExtensions.includes(ext)) {
      const relname = relative(cwd, fileName)
      return !isScoped(relname) || shouldIgnore(relname)
    }
    return true
  }
```

Is this acceptable?

**Comment by cspotcode** [comment]
Absolutely, we're happy for the help.

`ignored()` will be called a lot.  Instead of calling `getExtensions()` with it, we can make the call outside of `ignored`.  Maybe you were already planning to do this and the code you posted was a quick example.

I'm not sure if extname will handle `.d.ts` correctly.  I'm not sure if it needs to, either.  If we're trying to load a `.d.ts` file, then something has gone wrong elsewhere, right?

Other than that, looks good to me.

**Comment by concision** [comment]
My thought process was to invoke `getExtensions()` from inside `ignored()`, in case someone wanted to monkey patch the exported function for some reason. I will make the call outside of `ignored()` since that is both unlikely and unconventional.

`path.extname()` seems to only retrieve the first level extension, so `extname("typings.d.ts")` resolves to `.ts`. Is there a scenario where secondary extensions (other than maybe `.d.ts`) should _not_ be sent to the TypeScript compiler? This seems to be a non-issue with `require.extensions`, since the resolve algorithm will try to find the longest matching extension, allowing users to inject their own handler (e.g. `require.extensions['.secondary.ts'] = ...`). I suppose the responsibility should be passed on to the end user to order their ESM loaders correctly such that any secondary extensions are handled _before_ reaching the ts-node ESM loader?
