### ISSUE TITLE
Executables without extension

### ISSUE THREAD

**Issue by ValeriiVasin** [TypeStrong/ts-node#116]
I found that `ts-node` works only for files with `.ts(x)` extension. And it is not possible to create binary/executable file, e.g. `./bin/my-ts-executable` (without extension) but with shebang `#!/usr/bin/env ts-node`.

It works fine with `babel-node` shebangs.

Is there some limitations by TypeScript compiler or smth?

**Comment by blakeembrey** [comment]
No, it's a limitation of Node. It requires an extension to be able to run the correct extension loader. The only workaround for this may be to override `.js` - unless someone knows a better approach.

**Comment by zixia** [comment]
I ran into this issue today.

shebang works fine as long as the filename is in '.ts' extention, in this example, "t.ts".
```
#!/usr/bin/env ts-node
console.log('ohai from TypeScript')
import * as http from 'http'
```

But if rename "t.ts" to "t", and run "./t”, will get this error:
```
./t:3
import * as http from 'http'
^^^^^^
SyntaxError: Unexpected token import
```

It looks when run without extention, the script is treated as javascript instead of typescript, no mater what `shebang` we use.

can we find some way to "fake" the file extention name to node? because I would like to use typescript without extention, like this: `./t` :)

**Comment by thraaawn** [comment]
Running into the same issue: I would like to drop the .ts extension from some scripts, but can't. Any usable workaround/fix known?

**Comment by blakeembrey** [comment]
@thraaawn Same as my previous comment, no. It's a limitation of `node` that it treats unknown files as `.js`. The only workaround would be to enable `allowJs` with TypeScript (haven't tested it, but theoretically).

**Comment by ValeriiVasin** [comment]
Any idea how `babel-node` bypasses this limitation?

**Comment by blakeembrey** [comment]
Because it registers the `.js` extension like I mentioned above?

**Comment by ValeriiVasin** [comment]
would not it be a good fit for the `ts-node` to same to allow people write custom executables without an extension? Even though such a "hack" if you will.

Not sure is it hack or not b/c i have not really get what you meant :)

**Comment by blakeembrey** [comment]
No. That means every file runs through TypeScript, even JavaScript files. If you want that, use `allowJs` as I suggested above.

**Comment by ValeriiVasin** [comment]
Examples how to do such executables even through some tsconfig options would be much appreciated.

I tried this:

* created `bin/test` file with proper execution rights
```js
#!/usr/bin/env ts-node

console.log(1 + 2);
```

* added `allowJs` option to `tsconfig.json`:
```
"allowJs": true
```

* added npm script (to use local ts-node from node_modules/.bin - could be used through $PATH modification as well)
```
"test-it": "./bin/test"
```

* run
```
npm run test-it
```

it took quite a while before i got an error:
```
/Users/vvasin/Projects/ts-node-test/node_modules/typescript/lib/typescript.js:55445
                throw new Error("Could not find file: '" + fileName + "'.");
                      ^
Error: Could not find file: '/Users/vvasin/Projects/ts-node-test/bin/test'.
    at getValidSourceFile (/Users/vvasin/Projects/ts-node-test/node_modules/typescript/lib/typescript.js:55445:23)
    at Object.getEmitOutput (/Users/vvasin/Projects/ts-node-test/node_modules/typescript/lib/typescript.js:59348:30)
    at getOutput (/Users/vvasin/Projects/ts-node-test/node_modules/ts-node/src/index.ts:302:32)
    at /Users/vvasin/Projects/ts-node-test/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/Users/vvasin/Projects/ts-node-test/node_modules/ts-node/src/index.ts:502:17)
    at Module.m._compile (/Users/vvasin/Projects/ts-node-test/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vvasin/Projects/ts-node-test/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

what am i doing wrong here?

**Comment by blakeembrey** [comment]
I'll have to play around with it later, but it looks like it is going through TypeScript as a result. As for why the file isn't found, perhaps there's an issue reading it?

**Comment by blakeembrey** [comment]
I'm going to close this. In your stack trace you can see that all files are being compiled with TypeScript (see `ts-node` in your stack trace - it did go through the `ts-node` loader) if you configure it using `allowJs`. Again, this is just how node works - it'll use the extension loader defined otherwise `.js`. We can't make it use `ts-node` as a result. One hack, if there's enough request, would be to expose a `ts-js-node` or similar executable that's made with `allowJs: true` by default, but I'm not sure many people want that - for one, it'd start intercepting **all** `.js` files, not just the entry file without an extension.
