### ISSUE TITLE
Making ts-node work with loose typescript declaration files

### ISSUE THREAD

**Issue by lbfalvy** [TypeStrong/ts-node#1176]
### Desired Behavior
If tsc can compile using loose declaration d.ts files, there's no reason for ts-node not to do it. This only makes the package useless in many situations that involve both ts and node which is plain stupid.

### Is this request related to a problem?
I have a project that uses nodemon and recompiles typescript on edit. It uses d.ts files that just contain declarations of all global interfaces. Why wouldn't it do that, if tsc can handle it anyway. I tried to introduce ts-node to the project to shorten restart time because I thought that it combines typescript and node rather than inventing its own semi-compatible import behavior and failed because it seemingly doesn't support this perfectly standard typescript environment.

### Alternatives you've considered
I don't think there's an alternative, as it stands, code running in ts-node will only ever be aware of types declared or imported in that file.

**Comment by cspotcode** [comment]
Your tone is inappropriate.  In future, be more civil when asking questions.

Do you have a reproduction?  Have you tried `--files`?  The option can also be specified via your tsconfig file.

**Comment by lbfalvy** [comment]
I'm sorry, I am a bit frustrated.
I have tried --files on the command line which didn't work for some reason, however using `tsconfig.js/ts-node.files` solved the problem.

**Comment by cspotcode** [comment]
It's ok.  The `--files` quirk is a common source of frustration and we might change the behavior in the future.  It was done as a performance optimization to speed up `ts-node`, since in the common case, we can avoid compiling files that are never imported.  It technically doesn't change tsc's resolution behavior, it just overrides "files" and "include" arrays to only include your entry-point, pulling in all other files when they're resolved.  Another way to trigger inclusion of files without `--files` or `import` is to `/// <reference>` them.

`--files` predates typescript's "incremental" and "composite" options, and I'm pretty sure it's incompatible with them.  We have plans to support incremental/composite eventually (classic open-source problem, gotta find free time and I don't get paid) so we might make `--files` default when we do that.

**Comment by aruniverse** [comment]
Hi @cspotcode  any update on this?
