### ISSUE TITLE
ts-node doesnt use "foo.ts", if "foo" exists

### ISSUE THREAD

**Issue by backbone87** [TypeStrong/ts-node#1219]
### Expected Behavior
files:
- ./foo.md
- ./foo.md.ts
- ./index.ts

doing `import './foo.md'` in `./index.ts` should pick `./foo.md.ts` (this is what tsc does).

### Actual Behavior

doing `import './foo.md'` in `./index.ts` picks `./foo.md`

### Steps to reproduce the problem
`./foo.md`:
```
This is not TypeScript
```
`./foo.md.ts`:
```ts
export 'This is TypeScript';
```
`./index.ts`:
```ts
import './foo.md';
```

### Specifications

* ts-node version: ^9
* node version: ^14
* TypeScript version: ^4
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "strict": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "incremental": true,
    "baseUrl": ".",
    "outDir": "dist",
    "types": ["node"],
    "paths": {
      "@/*": ["src/*"],
      "@@/*": ["*"]
    },
    "lib": ["esnext"],
    "plugins": [{ "transform": "ts-transform-paths" }]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}

```
* Operating system and version: Win10 WSL2 Ubuntu

**Comment by cspotcode** [comment]
This is a node behavior, right?  Node will do this?

**Comment by backbone87** [comment]
does ts-node use node APIs for module resolution? because tsc uses `./foo.md.ts`

**Comment by cspotcode** [comment]
Node handles runtime resolution to match what happens when you compile your
code with tsc and then run it with node.  We aim for compatibility with the
two-step tsc && node, which is always going to be more performance and
suitable for production.

What happens when you compile the example using tsc and then run it with
node?  (Without setting outDir, since that's a separate concern)

**Comment by backbone87** [comment]
node loads `./foo.md` over `./foo.md.ts`.

>  always going to be more performant
idk how this has a performance impact, since you need to intercept the file loading anyway? so even if node resolves to `./foo.md` over `./foo.md.js` (not ts), then ts-node should behave like tsc and use `./foo.md.ts` when `./foo.md` is requested.

**Comment by cspotcode** [comment]
In production, many projects choose to precompile their code using `tsc` so that compilation does not happen in production.  No compilation means they don't spend CPU cycles on compiling.

> ts-node should behave like tsc

We do, actually.  And we *also* behave like node, because we *also* have a responsibility to behave like node.  We need to maintain compatibility with the use-case described above, where code is precompiled by tsc and then executed by node.

Our responsibility is to be a drop-in for `tsc && node`.  This means we use tsc's resolution rules for typechecking and node's for execution.

**Comment by cspotcode** [comment]
Closing this as answered.  If there's more we need to do here, we can reopen.
