### ISSUE TITLE
`require.extensions` is deprecated

### ISSUE THREAD

**Issue by NickHeiner** [TypeStrong/ts-node#1302]
This project works via `require.extensions`: [docs](https://github.com/TypeStrong/ts-node#how-it-works), [code](https://github.com/TypeStrong/ts-node/blob/03355c15210731d948713a5edc624d4f215d1113/src/index.ts#L404-L425). However, the [Node docs](https://nodejs.org/api/modules.html#modules_require_extensions) say that `require.extensions` is deprecated.

![image](https://user-images.githubusercontent.com/829827/116939062-8e398f80-ac20-11eb-9526-8132c3d7a17a.png)

Does this project have a path forward towards using a non-deprecated approach?

**Comment by cspotcode** [comment]
Correct, that has been the case for an extremely long time and node does not offer alternatives.  Unless you're referring to ESM loaders, in which case yes, we have one of those.  See #1007 

Although it is deprecated, experience shows that it is also stable, and has been that way for years.  If you're concerned that this deprecation is a risk, don't worry.  All the evidence suggests that this API surface is not going anywhere.

If you're curious about this topic, you may want to check node's issue tracker, since it's possible that users have requested a non-deprecated API surface to replace this one.  The node folks might have some thoughts on why they opted to keep this stable, deprecated API surface instead of creating a replacement.  You can also dig deeper into our issue tracker since this has already been asked here.

**Comment by NickHeiner** [comment]
That's fair. Thanks for the thoughtful analysis!
