### ISSUE TITLE
--emit option is not emitting files

### ISSUE THREAD

**Issue by Janpot** [TypeStrong/ts-node#1532]
### Search Terms

emit

### Expected Behavior

When you run the command with `--emit` options, a folder .ts-node is created that contains the transpiled code.

### Actual Behavior

No such folder is created

### Steps to reproduce the problem

```
mkdir ts-node-repro
cd ts-node-repro 
npm init --yes
npm add ts-node typescript
npx tsc --init
echo 'console.log("hello")' > index.ts
npx ts-node --emit index.ts 
ls .ts-node
```

Result:

```
ls: .ts-node: No such file or directory
```

### Specifications

```
ts-node v10.4.0
node v16.5.0
compiler v4.4.4
```
* Operating system and version: MacOs 11.6

Related issue: https://github.com/TypeStrong/ts-node/issues/1531

**Comment by cspotcode** [comment]
Closing as tracked by other tickets.

There's one about adding a `ts-node-emit` / `ts-node --emit` command #1175 

Docs already note that `--emit` requires `--compilerHost`

**Comment by jbriales** [comment]
Even though the docs already state that `--emit` requires `--compilerHost`, as a beginner I struggled to find why this feature was not working for me.
The reason was that I had set up the config to run with `--cws`. After reading above, I see why that didn't work.

I'd suggest to improve the docs in this sense:
- State that for `--emit` to work you cannot be using `--transpileOnly` (or `--cws`)
- I'd clarify that the `.ts-node` folder will appear in the CWD. Otherwise, I confused this with some "global" output folder in the installation folder of `ts-node` or similar. Specially when I didn't see anything locally, because `--cws` prevented it :) And I had never run with `--emit` before.
