### ISSUE TITLE
dynamic import is not working with register

### ISSUE THREAD

**Issue by ivanjeremic** [TypeStrong/ts-node#1548]
I don't know if it is a bug or even if it can be fixed but the modern dynamic import is not working with register.

```ts
async function nodeApp() {
 require('ts-node').register({
   transpileOnly: true
 })

 // changing this line to require works.
const { mod } = await import("./tsfile");

mod()
}
```

**Comment by cspotcode** [comment]
Not a bug, node forces us to use a different API for native ESM which is impossible to enable at runtime.  Using the ESM loader is what you want.  All the info you need is in the docs and in #1007.

**Comment by ivanjeremic** [comment]
> Not a bug, node forces us to use a different API for native ESM which is impossible to enable at runtime. Using the ESM loader is what you want. All the info you need is in the docs and in #1007.

Thanks hope it will take a long time if ever when require gets deprecated.

**Comment by FFdhorkin** [comment]
> Not a bug, node forces us to use a different API for native ESM which is impossible to enable at runtime. Using the ESM loader is what you want. All the info you need is in the docs and in #1007.

What is in #1007 and the docs does not seem to cover this use case. As I mentioned on that discussion thread, this doesn't work because `importESM` does not exist:
`const dynamicallyImportedEsmModule = await require('ts-node').importESM('./specifier-of-esm-module', module);`

I tried the `importEsm` method that I found [here](https://github.com/TypeStrong/ts-node/discussions/1290), but that doesn't work, either. I still get `Unknown file extension ".ts"`

**Comment by FFdhorkin** [comment]
> Not a bug, node forces us to use a different API for native ESM which is impossible to enable at runtime. Using the ESM loader is what you want. All the info you need is in the docs and in #1007.

What is in #1007 and the docs does not seem to cover this use case. As I mentioned on that discussion thread, this doesn't work because `importESM` does not exist:
`const dynamicallyImportedEsmModule = await require('ts-node').importESM('./specifier-of-esm-module', module);`

I tried the `importEsm` method that I found [here](https://github.com/TypeStrong/ts-node/discussions/1290), but that doesn't work, either. I still get `Unknown file extension ".ts"`
