### ISSUE TITLE
Issue related to --loader ts-node/esm not being able to find a module

### ISSUE THREAD

**Issue by WesleyKlop** [TypeStrong/ts-node#1711]
### Search Terms

I searched for "ts-node/esm", "loader", but could not find the same behavior I'm seeing.

### Expected Behavior

When using `node --loader ts-node/esm` I expect it to be able to import `.ts` files without an extension.

### Actual Behavior

When using `node --loader ts-node/esm` it does not import ts files when using no extension or the `.ts` extension but it DOES work when using the `.js` extension even though that file does not exist.

### Steps to reproduce the problem

PoC: https://github.com/WesleyKlop/ts-node-esm-poc

I think I also know _where_ the error might be coming from. In the function `finalizeResolution` on line 373 it calls `resolveReplacementExtensions` which only acts when the .js file extension is in the pathname. This gives unexpected (to me) results. 

Also using the swc integration seems to fix being able to import using a .ts extension.

Bonus: I also added dynamic imports to my poc, which seems to work with both .ts and .js extensions but not without extensions, same as when enabling swc. Probably because the import can't be seen as "bad" by the typescript compiler.

### Minimal reproduction

See repo in previous step

### Specifications

* ts-node v10.7.0
* node v17.6.0 but also tried v16.14.2 
* compiler v4.6.3
* tsconfig.json, if you're using one:
```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "es2022",
        "moduleResolution": "node"
    }
}
```
* Operating system and version: MacOS 12.x
* If Windows, are you using WSL or WSL2?: -

**Comment by cspotcode** [comment]
TypeScript's typechecking behaviour is dictated by TypeScript, so you'll have to take this up with them.

Gonna go ahead and close this because everything is working correctly here.  I've fielded this question many times before and can't justify dedicating any additional time to it.  However, I understand that you may want to discuss this further with someone (not me) so I'll link to a relevant discussion on TypeScript's Github.

https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1094109271
