### ISSUE TITLE
Use .swcrc with the swc transpiler

### ISSUE THREAD

**Issue by davidtheclark** [TypeStrong/ts-node#1796]
### Desired Behavior

When I use the bundled swc transpiler, I'd like it to read configuration from my `.swcrc` file. Instead, [it looks like](https://github.com/TypeStrong/ts-node/blob/f34d87479b979fc2a9442f3f576893dcf6b620a8/src/transpilers/swc.ts#L66-L149) the plugin creates its own swc config based on ts-node's configuration. This means I need to put my swc configuration in two places, instead just in my `.swcrc` file.

### Is this request related to a problem?

Just configuration duplication.

### Alternatives you've considered

Using swc packages directly instead of ts-node's swc transpiler. But ts-node's source maps work in my context (VS Code debugger) and swc's do not (as far as I can tell), so I want to stick with ts-node.

### Additional context

ts-node was complaining about `import` statements not being legal. It took me a bit to realize this meant it wasn't reading my `.swcrc` file, which specified `"module": { "type": "commonjs" } }`. To fix this, I set `TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}'`.

**Comment by cspotcode** [comment]
I'd accept a PR that adds this as an option, but I still want the default to be zero-config.

In your case, you shouldn't need to specify `module: {type: "commonjs" }` in .swcrc if you package.json and tsconfig.json are configured correctly.  I feel like there might be a more pragmatic solution here, maybe some tsconfig confusion that we can clear up.

**Comment by davidtheclark** [comment]
I think the problem is that I'd rather not have a `tsconfig.json` file in addition to an `.swcrc` file.

> I'd accept a PR that adds this as an option, but I still want the default to be zero-config.

That sounds reasonable 👍

**Comment by cspotcode** [comment]
I doubt we'll ever support avoiding a tsconfig file, that's too much
complexity for too few users.  Plus it's a confusing recommendation to say
to anyone to avoid a tsconfig file in a TS project.  Just like any
preference, it's yours to have if you really want it, but it's more effort
for us to support that use-case.

**Comment by davidtheclark** [comment]
OK -- yeah, maybe the root problem is that swc tools do not read `tsconfig.json` (unless I'm doing it wrong). And I understand that that's not your problem. I will keep fiddling, and if I can't figure something out may try to come up with a PR.

**Comment by ShravanSunder** [comment]
related #1800

**Comment by cspotcode** [comment]
@davidtheclark it looks like your problem will be solved by adopting a tsconfig.json.  ts-node will read it and behave accordingly.  If you run into a situation where you feel like you need two *different* tsconfig files, because you already have a tsconfig for some other purpose, and yet you need ts-node or swc to behave *differently* than what is in your tsconfig, then you may want to know that ts-node allows overriding options within your tsconfig, using a "ts-node" sub-object.  In general, everything can be configured in that one file: https://typestrong.org/ts-node/docs/configuration#via-tsconfigjson-recommended

This setup is simple enough when done correctly.  If you run into any trouble, please either ask on the [Typescript Discord](https://discord.gg/typescript) or start a [discussion thread](https://github.com/TypeStrong/ts-node/discussions).

I'll go ahead and close this ticket, but we can accept a PR (with proper tests!) that adds swcrc support as an option.  So if you decide you want to implement that, feel free to open a new issue to discuss the best approach.
