### ISSUE TITLE
.editor mode takes previous command as a first line of a block

### ISSUE THREAD

**Issue by skovorodkin** [TypeStrong/ts-node#189]
A way to reproduce:
```
$ ts-node
> function a(str) { console.log(`Hello, ${str}!`); }
undefined
> a
[Function: a]
> .editor
// Entering editor mode (^D to finish, ^C to cancel)
('world')
Hello, world!
undefined
>
```

Expected behavior:
```
$ node
> function a(str) { console.log(`Hello, ${str}!`); }
undefined
> a
[Function: a]
> .editor
// Entering editor mode (^D to finish, ^C to cancel)
('world')
'world'
>
```

**Comment by blakeembrey** [comment]
This isn't anything to do with `.editor`. You can reproduce without. This is more an issue with how TypeScript rewrites the expression and then we end up re-evaluating it. Open for suggestions to fix, but it's not really easy to do since TypeScript requires all the previous context for type information.

My initial thought is to abuse references here. Every time you hit "enter", we generate a new dynamic file that autoincrements (E.g. `1.ts`, `2.ts`, `3.ts`, ...) and use references to the previous file. It might work.

**Comment by blakeembrey** [comment]
Just in case there's any suggestions from the TypeScript team too /cc @mhegazy

For reference, the current REPL is awesome, but a complete hack on the TypeScript compiler side. There's no way, that I knew of, to be "append-only" with compilation so I hacked around this issue by using a `diff` library and re-compiling the whole file each time. Works great, except when you run into a situation like this (it's basically an ASI fail which results in a different compilation on the next line).
