### ISSUE TITLE
use tap test runner

### ISSUE THREAD

**Issue by netdesk** [TypeStrong/ts-node#195]
Hi,
I use ts-node to compile my source, and I would like to use ts-node also for "wrapping" around my tape tests. As tap has some conveniences over using tape directly (like code coverage), it would be nice to use ts-node in combination with tap. I tried like in the README with tape, exchanging the tape executable with tap like this:
`ts-node node_modules/.bin/tap some-test.ts`

The test file some-test.ts is as simple as this:
```typescript
import {test} from "tape";
test("Tests up and running", function(t) {
    t.plan(1);
    t.ok(t, "Yope!");
});
```

Running this, the test result gives no tests:

```plain
total ................................................. 0/0
  0 passing (150.283ms)
  ok
```

Running them with tape like `ts-node node_modules/tape/bin/tape some-test.ts` correctly shows the one test in the test file.

Am I missing some point? How would one use ts-node with tap to use features like coverage?

**Comment by netdesk** [comment]
I created a minimum example to try this: https://github.com/netdesk/example-ts-node-tap
Just clone it, `npm install` it, and then compare the tests run by those two commands:
`npm run test-with-tape`
and
`npm run test-with-tap`

It seems that the some-test.ts file is never touched in the script using tap as the console.log statement is never shown. If you compile to js and run using tap directly with this npm script, then you see how it should look:
`npm run test-with-tap-js`

**Comment by blakeembrey** [comment]
@netdesk The obvious test here is to try doing just `node` instead of `ts-node` and you'll see it still fails. From that, it's pretty simple to guess what's wrong is to do with file extensions and not with `ts-node`. Have you tried reading through the `tap` docs? Perhaps there's a feature ignoring certain extensions by default?

**Comment by blakeembrey** [comment]
To clarify, most of external tooling usually needs a specific flag to enable other extensions. For example, things like https://github.com/istanbuljs/nyc#support-for-alternate-file-extensions-jsx-es6.

**Comment by blakeembrey** [comment]
Reading https://github.com/tapjs/node-tap/blob/master/bin/run.js#L698-L708, it would appear that it'll ignore the file unless it's executable. If I make your test file executable, I can see a failure, but the reason for that failure appears to be suppressed. I'm pretty confident that's because every process is spawned, which lead me to https://github.com/tapjs/node-tap/issues/313 which your question was already answered there.

**Comment by netdesk** [comment]
Whop, this is what facepalm-emoticons are for. Thanks. I tried the shebang solution, but missed the execution "bit" - in all it's ambiguity. I'll try to find out why the test fails and if it's a ts-node thing (don't think so) I'll come back here.
Anyway, thanks mate!

**Comment by blakeembrey** [comment]
@netdesk If there is something that needs to be fixed, definitely let me know! It seemed to work when I run it _only_ using `node` though and the as `./test.ts`. So, I'm not sure what it is and wasn't sure how to figure it out either - it just sort of hangs. I suspect there'll be issues with coverage in this approach also, since tap won't know it can cover `.ts` files.

**Comment by zixia** [comment]
thanks for the analyse @blakeembrey @netdesk 

It worked in my test:
https://github.com/tapjs/node-tap/issues/313#issuecomment-250067741
