### ISSUE TITLE
@swc/core@1.3.51 does not return sourcemap for type-only files, causes error in `updateSourceMap`

### ISSUE THREAD

**Issue by erikthiem-immuta** [TypeStrong/ts-node#1996]
### Search Terms
SWC

### Expected Behavior

I am using ts-node with the `--swc` flag. I expect it to work. It works fine for me on SWC < 1.3.50

### Actual Behavior
I tried upgrading to SWC >= 1.3.50 today and it caused ts-node to not work. I unfortunately did not see much useful output. If there is a way to get more useful output to fix this, I am happy to try it.

### Steps to reproduce the problem
Upgrade to SWC >= 1.3.50

### Minimal reproduction
Be on ts-node version `10.9.1` and SWC version `1.3.50` and try to use ts-node with the `--swc` flag.

### Specifications

* ts-node version: 10.9.1
* node version: 18.x
* TypeScript version: 4.8.4
* tsconfig.json, if you're using one:
```
"ts-node": {
    "swc": true
}
```
* package.json:
The relevant part would be:
```
`... node_modules/ts-node/dist/bin.js --swc --transpile-only index.ts`
```
* Operating system and version: Mac
* If Windows, are you using WSL or WSL2?:

**Comment by koh110** [comment]
I have same issue.
After changing the version of `@swc/core@1.3.51`, I encountered an error in `--swc` mode.
The cause of the error seems to be `import` a file that only `exports` types.

Since a file that only exports types does not generate a SourceMap file when using `@swc/core@1.3.51`.
So it seems that `updateSourceMap` throw error because `undefined` is given to JSON.parse.
[ref](https://github.com/TypeStrong/ts-node/blob/97f9afd046b66a0fe05a7d76e7a32f94b872016f/src/index.ts#L1571-L1574)

I have confirmed that the error does not occur when passing `{}` instead of `undefined`.
```javascript
function updateSourceMap(sourceMapText: string, fileName: string) {
  const sourceMap = JSON.parse(sourceMapText ?? {});
```

I want to send PR, but I still can't think of how to write tests.
