### ISSUE TITLE
Project settings for running under mocha

### ISSUE THREAD

**Issue by arusakov** [TypeStrong/ts-node#200]
`ts-node` doesn't load files from `include` field of `tsconfig.json`

**Comment by blakeembrey** [comment]
Can you create a production? Can you provide more information on what exactly isn't included? It should _just work_, but that rarely happens with TypeScript. However, I was pretty sure the parser method I use is the one that expands `includes`.

**Comment by arusakov** [comment]
@blakeembrey 
I have index.spec.ts in ./test dir:
```
describe('title', () => {
// ..
});
```
And tsconfig.json in same dir:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "outDir": "../lib",
        "strictNullChecks": true,
        "target": "es2015"
    },
    "include": [
         "../typings/globals/node/**/*",
         "../typings/globals/mocha/**/*",
        "./**/*"
    ]
}
```

I try to execute mocha with cmd:
`./node_modules/.bin/mocha --compilers ts:ts-node/register`

And have error:
```
/Users/arusakov/WebstormProjects/project-x/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
test/index.spec.ts (3,1): Cannot find name 'describe'. (2304)
............
```

I fix it by env variable: `TS_NODE_PROJECT=./test` 

Sorry, for uncompleted report. I change issue title.

May be we need some docs about this case?
Can I set `project` setting for running under mocha without env variable?

**Comment by blakeembrey** [comment]
There should be documentation about the `project` setting, feel free to submit a PR to improve it. It doesn't know how to magically find the `tsconfig.json` file, so it's usually based on your current working directory (the same way `tsc` does it). You can't change any other settings sadly, there's no real way to set it up otherwise in these cases where the compile is a dependency and not directly the runner. You _could_ do `ts-node node_modules/.bin/_mocha` but you'd lose some of the extra benefits from using the `mocha` args.
