### ISSUE TITLE
Error messages not appearing for syntax errors when using Mocha's `--watch` mode

### ISSUE THREAD

**Issue by mylesmegyesi** [TypeStrong/ts-node#248]
I'm using the ts-node to compile Mocha tests written in TypeScript as described in the [README](https://github.com/TypeStrong/ts-node#mocha), however when there is a compilation error in a test file, no error message is displayed in watch mode (works fine with a single run). I've done some investigation and it appears the problem is two fold:

1) The mocha watcher catches the exception that is thrown by `require`, but [only prints `e.stack`](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L423). The works because Node's require function puts the error message and stack trace into `e.stack`.
2) ts-node only sets [`e.message` instead of `e.stack`](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L651), so the error message is lost. This was a change introduced [here](https://github.com/TypeStrong/ts-node/commit/1553197eceb9d164a020f26168ee5acecefa090f) and included in the `1.7.0` release.

Would you consider setting the `.stack` property in a way that is similar to Node's `require` function? This way, there is no difference between `require`ing a `.js` file and a `.ts` file from the consumer's perspective.

**Comment by blakeembrey** [comment]
The issue is that `ts-node` is wiping out `err.stack`. Usually `err.stack` is populated from the message automatically, but it was creating a lot of noise. I'm happy to tidy it up so it uses `err.message` directly instead of wiping it out entirely, I can actually just revert it so the stack prints too but it doesn't typically include anything useful.

**Comment by mylesmegyesi** [comment]
Thanks!
