### ISSUE TITLE
Namespaced modules do not contain exports

### ISSUE THREAD

**Issue by sdellis** [TypeStrong/ts-node#249]
I have no problem accessing exports when my modules are not namespaced.  However, when namespaced, no errors are thrown and I can set my module to a var, but I just get `mymodule.foo` is undefined.  Has anyone tested ts-node with namespaces?

**Comment by blakeembrey** [comment]
It doesn't work because node doesn't understand it. You should probably look into how the node.js module system works.

**Comment by havenchyk** [comment]
@blakeembrey does it mean that if I have a namespace defined in `typings` folder and `tsc` sees it, with `ts-node` I'll need to import it explicitly?

**Comment by blakeembrey** [comment]
No, you would be able to access any types as normal if they’re global. That’s how `@types/node` works. It just can’t work at runtime because node.js uses a module system and isolates modules, while TypeScript would assume the namespaces are automatically global everywhere because of browser backward compatibility.

**Comment by havenchyk** [comment]
@blakeembrey I found that adding my typings to `typings/my_namespace_name/index.d.ts` and 

```
"typeRoots": [
      "./node_modules/@types",
      "./typings"
    ]
```

works great with `ts-node` without an explicit importing, but I didn't find an explanation

**Comment by blakeembrey** [comment]
The explanation is in the README.
