### ISSUE TITLE
Sometimes, a type error will not be caught.

### ISSUE THREAD

**Issue by geon** [TypeStrong/ts-node#281]
I will be refactoring something, and forget to make the change somewhere, but the code keeps running. Then, several commits later, I get the error.

I can't reproduce the issue. Checking out a good commit before the error, then a broken commit makes ts-node catch the type error like it should have from the beginning.

It has happened to me 4-5 times in the last 10 days.

I run ts-node with nodemon via npm like this:

```js
"scripts": {
    "dev": "cd src && PORT=3000 nodemon --exec 'ts-node' index.ts"
}
```

**Comment by blakeembrey** [comment]
Sounds like it'd probably be the cache. It's the reason I was reluctant to add it initially. If the files hit the cache, the won't be type-checking as a result since they've already been generated. However, the cache might be invalid because of changes in dependent files that have caused type errors. Does that sound like the issue you're running into?

I'm not 100% if there's any way to solve it other than disabling the cache. Something I mulled over a year ago was making the "fast" mode default (no type checking) and keeping the current mode as a back-up.

**Comment by geon** [comment]
> Does that sound like the issue you're running into?

Absolutely. It was exactly what I was doing.

I'll try using `--no-cache`.

**Comment by blakeembrey** [comment]
Great, thanks for the confirmation. That's a bit of a bummer. On a related note, if I were to make "fast" mode the default (no type information) - would that be useful? Then I could possibly disable the cache for the basic mode.

**Comment by geon** [comment]
I think there should be either complete type checking or none at all. Having cached compilation that can sometimes be invalid is a bit non-obvious. Which one is the default isn't that important.

Personally, I think it would make more sense to have full type checking as the default, with an optional fast mode for production, or quick dev on larger code bases. But as I said, either default would be fine.

The more I think of it, caching makes no sense if it isn't invalidated by changes to dependencies. Having types work across files is kind of the whole point of typescript. Types for a single file, I might be able to keep in my head. Multiple files across the whole project - not so much.
