### ISSUE TITLE
What are the semantics of multiple registrations?

### ISSUE THREAD

**Issue by lddubeau** [TypeStrong/ts-node#286]
Consider the following scenario:

1. `gulp` starts and calls `ts-node`'s registration so that it can handle a `gulpfile.ts`.

2. `gulpfile.ts` imports the `karma` module to invoke Karma through it's programmatic API (rather than spawn a process to run it).

3. Karma calls `ts-node`'s registration so that it can handle a `karma.conf.ts`.

4. `gulpfile.ts` then imports another TypeScript module. It could be a local utility module or a task locally stored in the `./gulptasks` subdirectory (a common way of organizing Gulp tasks).

5. Hilarity ensues. The module loaded at step 4 will most likely bork.

I've put up an example [in this repository](https://github.com/lddubeau/ts-node-multiple-registers).

This raises questions.

1. Is it ever meaningful to register multiple times in the same VM?

2. Should `ts-node` raise an error on subsequent registrations?

3. Are there patterns of reregistration that should be accepted silently? e.g. if a registration is performed with some options and a second registration is performed with the *same options*, should it be accepted silently and be a no-op? After all, both registration requests asked for the same thing.

4. Can we come up with some rules that would allow for harmony between multiple code bases that want to use `ts-node`? Looking at the issue at hand here it seems to me that Karma should distinguish between it being run as an *independent process* in which case it may register `ts-node`, and it being loaded as *part of another process*, in which case it should defer to whatever the main process does.

**Comment by blakeembrey** [comment]
1. Not that I can think of, 99% sure it's an error.
2. If there's an easy way to tell, sure. Failing silently sounds better because I wouldn't want to force people to be unable to work because of projects registering `ts-node`.
3. I guess, but same as above - need a way to be able to tell this.
4. Yes, it seems like a Karma issue. Usually, if you're running the CLI it would "auto-register" (e.g. Gulp) and if you're using it programmatically it would not. `ts-node` works the same way itself (you can use via `node -r ts-node/register` or `ts-node`).

**Comment by slavafomin** [comment]
This is a very interesting subject. I've encountered some weird behavior of `ts-node` and started debugging. After a while, I've found out that some dependencies are calling `ts-node.register`, so that it's getting registered multiple times.

I believe if it's not an intended behavior (as @blakeembrey confirmed above) there should be definitely a warning or an error about subsequent registrations. Falling silently is a very dangerous thing to do, because it leads to an unpredictable results in runtime.

**I would strongly suggest to:**

1. Re-open this issue
2. Change the issue's label to a more meaningful one
3. Add functionality to log warning messages (I believe this should be an easy thing to do using global flag, please correct me if I'm wrong)

**Comment by blakeembrey** [comment]
To revise the comment I left originally, there is a valid way to register multiple times via the “scope” option (I believe it’s currently not documented though). I do also believe it should be an error for multiple invalid registrations, if someone would like to make a pass of the functionality. It’d need to support multiple registrations that don’t “conflict”.

**Comment by blakeembrey** [comment]
Also, this existing open issue is relevant: https://github.com/TypeStrong/ts-node/issues/409#issuecomment-575467589.

**Comment by slavafomin** [comment]
@blakeembrey So, if I set `scope: true`, then this specific registration of `ts-node` will handle only files loaded from the specified `cwd`, right?

**Comment by blakeembrey** [comment]
Correct, rather `dir`. So you can do `register({ dir: __dirname, scope: true })`. Basically, it'll only transpile files relative to that directory which can enable a multi-project setup where you register many times with the other instances ignoring each other. However, if there's overlap in `dir` you'll still run into issues with it transpiling twice and _probably_ breaking.

**Comment by slavafomin** [comment]
I see, thank you for explanation 👍
