### ISSUE TITLE
Older versions of Node.js

### ISSUE THREAD

**Issue by cypherq** [TypeStrong/ts-node#291]
Is there any chance that PR with ponyfills for older Node.js versions like 0.8.x - 0.12.x will be accepted if I'll provide such or you don't want to support those versions anyway?

**Comment by blakeembrey** [comment]
I don't think so. You can let me know what exactly does need changing, but since <= 4.0 is EOL I'd prefer to avoid it. IIRC, there's two places where I'm using explicit node >= 4 features and, I believe, one can't be ponyfilled. TravisCI would also need to ensure versions < 4 stay supported, but overall - unless it's tiny - I'd prefer to avoid the maintenance overhead of dead node versions.
