### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by Sitronik** [TypeStrong/ts-node#304]
I want to use Generic as below:

```typescript
function identity<t>(arg: T): T {
    return arg;
}
</t>
```

But I can't to use and I get this error:

```⨯ Unable to compile TypeScript
[eval].ts (2,1): '}' expected. (1005)
[eval].ts (1,27): Cannot find name 'T'. (2304)
[eval].ts (1,31): Cannot find name 'T'. (2304)
>     return arg;
⨯ Unable to compile TypeScript
[eval].ts (1,1): A 'return' statement can only be used within a function body. (1108)
> }
⨯ Unable to compile TypeScript
[eval].ts (1,1): Declaration or statement expected. (1128)
```

**Comment by blakeembrey** [comment]
This isn't a general TypeScript support forum. Please use StackOverflow for that. For starters though, you need to capitalize `T` in the generic and I'm not sure what the `</t>` is doing. For the other errors, it looks like it's caused because when an error is output you can't keep writing like nothing happened.
