### ISSUE TITLE
Errors (warnings?) hidden by tsc

### ISSUE THREAD

**Issue by martinheidegger** [TypeStrong/ts-node#314]
In postgraphql the recent commits were run through the tsc without an issue, even ts-node works with the `"--disableWarnings"` flag, but if that flag is not set we receive an Type error which is weird because this error should be thrown by the tsc as well. Could it be that this error is somehow obfuscated when running tsc?

**TypeScript Version:**  2.1.5

**Code**

https://github.com/calebmer/postgraphql/commit/4da7b611d5530f7dcd6542166c9b6da3eba683f2

**Expected behavior:**

TSC and ts-node exit with the same error.

**Actual behavior:**

tsc finishes without error, ts-node exits with error 

```
TSError: ⨯ Unable to compile TypeScript
src/postgres/inventory/collection/PgCollectionKey.ts (60,19): Cannot find name 'ObjectType'. (2304)
src/postgres/inventory/collection/PgCollectionKey.ts (66,17): Parameter 'value' implicitly has an 'any' type. (7006)
```

**Comment by blakeembrey** [comment]
Hey. Thanks for the report. I remember looking at this when it was reported and I was mentioned, and I since followed up on the `tsc`, but at the time I recall that the errors were actually 100% correct. I don't recall if maybe it was a specific `tsc` version, or something else, but I'm not sure what `ts-node` can do with this - the errors are just being output from TypeScript's API.

**Comment by blakeembrey** [comment]
Closing as unsolved or solve in TypeScript, will reopen if someone else discovers this issue again.
