### ISSUE TITLE
Imported same things from .js files and .ts files are not equal instances

### ISSUE THREAD

**Issue by pleerock** [TypeStrong/ts-node#432]
I have an issue and Im not sure what to do with it.

In typeorm there is an option to load all entities from a single directory, it can be used this way:

```json
{
   "entities": [
      "src/entity/**/*.ts"
   ]
}
```

If users are using ts-node they can specify .ts extension, if just node then .js

This code allows to load entities from a directory dynamically, for example if there is a `User.ts` file it will load it: 

```ts
const userLoadedByTypeORMPackage = require("/full-path-to-project/src/entity/User").User;
```

IMPORTANT: since typeorm is in node_modules source code is in javascript and previous code will run from lets say "entityImporter.js".

Now, when user in `app.ts` does following:

```ts
import {User} from "./entity/User";

const userRepository = getRepository(User);
```

`User` instance is not equal to `userLoadedByTypeORMPackage` !!!

And what important to note that its equal only if there is a `User.ts` file and no `User.js` in the `entity/` directory. If I remove User.js file everything works fine. 

As I understood when "require" is run from .js file it first try to load ".js" file, then ".ts" file. I don't think its correct behaviour and priority shall be given to .ts instead.

**Comment by blakeembrey** [comment]
This is expected behaviour. `ts-node` will not alter the `require` priority, as it's not possible to meet expectations - `.js` is always first loaded with node.js (regardless of CoffeeScript, Babel, whatever). I would recommend never compiling your `.js` file beside your `.ts` files, and if you must, don't specify `.ts` files to be required. If you do, do what the ORM does - require it using the full path including extension. Without the extension will act like node.js is meant to.

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/TypeStrong/ts-node/issues/389.
