### ISSUE TITLE
Making syntax error in mocha test exits mocha --watch

### ISSUE THREAD

**Issue by grigoryvp** [TypeStrong/ts-node#45]
Thanks for amazing code!

Right now, if I do syntax error in `mocha` test itself (ex `./test/sometest.ts`), `mocha --watch` will terminate due to https://github.com/TypeStrong/ts-node/blob/master/src/ts-node.ts#L198

Is this expected? Without ts-node `mocha` don't terminate on syntax errors in tests, it simply dumps stacktrace so programmer can fix an error and continue watch

**Comment by blakeembrey** [comment]
You're right, this has been reported before too. I'll change this code to only throw, throwing is a bit more ugly though since I can't format the output message properly. I'll see how close I can get and if anyone knows if there's a way to specify formatting of uncaught exceptions on node, let me know :+1:

**Comment by asvetliakov** [comment]
> if there's a way to specify formatting of uncaught exceptions on node, let me know
```typescript
/**
 * TypeScript diagnostics error.
 */
export class TSError extends BaseError {
....
   toString() {
       return printDiagnostics(this.diagnostics);
   }
}
```
This should do the trick
