### ISSUE TITLE
Common use case not documented - ts-node-register

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-node#478]
Seems like this is a common use case:

```js
 require('ts-node').register({
    // This will override `node_modules` ignoring - you can alternatively pass
    // an array of strings to be explicitly matched or a regex / glob
    ignore: /node_modules/
  });
```

if it's correct, we should put it in the README methinks

**Comment by blakeembrey** [comment]
This should not be a common use-case and it probably shouldn't be in the README. You can discover it through documentation, but compiling `node_modules` at runtime for `.ts` files isn't a practice I want to recommend anyone or support by default.

**Comment by alexanderby** [comment]
I had the following situation: I used components written with TSX which imported ES2015 code from node_modules and got `Unexpected token import`. I've switched tsconfig to `"module": "commonjs"` but it didn't help because imported code contained another ES2015 import. So, finally, `ignore` option helped me, I was lucky to find it here.

**Comment by blakeembrey** [comment]
@alexanderby The only way you should be importing ES2015 module code from `node_modules` is if it was published that way. If it was published that way, the intent could be for it to be consumed as ES2015 modules. Transpiling it to CommonJS can introduce inconsistencies there. Also, this option is in the README: https://github.com/TypeStrong/ts-node#cli-and-programmatic-options.

It was also in the README when this issue was logged: https://github.com/TypeStrong/ts-node/blob/c57ded2881debf773af7b8e01cb652d48f8655ca/README.md#configuration-options.

**Comment by blakeembrey** [comment]
Can you also share the command which you used to help you? I'm not sure how `ignore` helped.

**Comment by alexanderby** [comment]
My code was
```javascript
require('ts-node').register({
    compilerOptions: {
        module: 'commonjs',
        allowJs: true,
    },
    ignore: []
});
```
and then I was able to import *.tsx files with es2015 modules.
