### ISSUE TITLE
ts-node and babel-register almost working together

### ISSUE THREAD

**Issue by fgarcia** [TypeStrong/ts-node#585]
I am using Babel and Ts-Node together and it seems to work fine except for the stack traces. This is my entry point

```
require('ts-node/register/transpile-only')
require('babel-register', {
  extensions: ['.ts', '.js', '.tsx', '.jsx'],
})
```

As far as I know this is the right order of registration. First ts-node and later babel-register. Otherwise my code would fail because Babel would be trying to parse Typescript files before being transpiled

However in this setup my error stack traces are off. The `retrieveFile` of this line will always return `undefined`

https://github.com/TypeStrong/ts-node/blob/5af28eea6523db171a75d95e21f4533584894a1e/src/index.ts#L196-L201

I noticed however that If I load babel before ts-node, and avoid errors by not importing Typescript files from JS files, the sourcemaps do show up

is there a way to fix this?

**Comment by fgarcia** [comment]
OK! I've just solved my problem.

The problem is that ts-node is installing `source-map-support` but loading Babel afterwards breaks that installation.

I've just patched my ts-node to delay the installation like this:

```
  global.__TsNodeInstall = () => {
    sourceMapSupport.install({
      environment: 'node',
      retrieveFile: function(path) {
        return memoryCache.outputs[path]
      },
    })
  }
```

Now I can do this:

```
require('ts-node/register/transpile-only')

require('babel-register', {
  extensions: ['.ts', '.js', '.tsx', '.jsx'],
})

global.__TsNodeInstall()
```

This seems to fix all my stack traces problems. I can run ts-node with Typescript targeting `esnext` code and chain with Babel without losing my inline sourcemaps

**Comment by blakeembrey** [comment]
There's not anything I can see `ts-node` doing much better here. I'm not sure your source maps will work still either, since wouldn't it be pointing to the wrong position if both transpile to a different line (you might not be seeing it because, IIRC, babel tries to keep sources on the same line). I think this is something that may be fixed in `babel-register`.

If babel is compiling based on the output from `ts-node`, can you try the `inputSourceMap` option from https://babeljs.io/docs/usage/api/? The issue would appear that `babel` just tosses it away so you end up with incorrect lines.

**Comment by blakeembrey** [comment]
As for TypeScript itself accepting input source maps, it's probably blocked by https://github.com/Microsoft/TypeScript/issues/13944.
