### ISSUE TITLE
require a module which exports is a function get { __esModule: true }

### ISSUE THREAD

**Issue by UnightSun** [TypeStrong/ts-node#677]
test2.ts:

> import Koa from 'koa';
> import KoaBody from 'koa-body';
> export default async function(ctx: Koa.Context): Promise<any> {
>     ctx.body = { files: ctx.request.files, body: ctx.request.body, test: 1 }
> }

test3.ts:
> import Koa from 'koa';
> exports = async function(ctx: Koa.Context): Promise<any> {
>     ctx.body = {}
> }

main.js:
> require('ts-node').register();
> (async function () {
>     const test2 = require('./test2');
>     const test3 = require('./test3');
>     console.info('done');
> })();

while test2 is 
![image](https://user-images.githubusercontent.com/25891602/45140047-426e8800-b1e4-11e8-9ab0-9aad694efe98.png)
and test3 is
![image](https://user-images.githubusercontent.com/25891602/45140065-4e5a4a00-b1e4-11e8-946a-b7bdc0140786.png)

debug trace to /<node_internals>/module.js  line number: 600
Module.prototype._compile  returns undefined.

"ts-node": "^7.0.1",
"typescript": "^3.0.1"
node  v8.9.4

**Comment by blakeembrey** [comment]
This module uses the TypeScript compiler so you should replicate it using the compiler. We don’t alter any transpiled output so most likely it’s not an issue with `ts-node`. Going to close this out as is since I don’t see how it could be fixed here, but please feel free to follow up with whether it’s replicated using the TypeScript compile directly.
