### ISSUE TITLE
Truncate stack trace on compiler error

### ISSUE THREAD

**Issue by brainkim** [TypeStrong/ts-node#679]
I’ve got the `--pretty` flag set to show compilation errors, but a minor inconvenience is that the ts-node stack trace is huge and will cause me to scroll up to find the errors. It would be nice if pretty mode truncated the stack trace.
![screen shot 2018-09-10 at 1 34 19 pm](https://user-images.githubusercontent.com/2996754/45314010-91772e80-b4fe-11e8-90b3-914056124514.png)

**Comment by blakeembrey** [comment]
It’s unfortunately kind of difficult to render the error without the stack. If you have a solution, let me know.

**Comment by cspotcode** [comment]
This is really tricky because any code that does:

```
try {
    require('./typescriptfile');
} catch(e) {

}
```

has a reasonable expectation for `e` to be a normal exception with a `stack` and `message`.  The attempted solution (2) could theoretically replace the `stack` property with a custom getter that returns a fake (empty) stack one time only, reverting to normal behavior immediately after the first "get."  Feels like a crazy hack, but it would mean that node's "uncaught error" rendering would omit the stack trace, whereas all other code paths would have access to the normal stack.

**Comment by cspotcode** [comment]
Coming back to this, the long stack trace is due to someone or something overwriting `Error.stackTraceLimit`, right?  Possibly, we could swap out `Error.stackTraceLimit` when we create type errors.

```
const valueFromBefore = Error.stackTraceLimit;
Error.stackTraceLimit = 2;
err = new Error('type error happened');
Error.stackTraceLimit = valueFromBefore;
```

Seems like a hack, though, and makes us non-standard.

**Comment by cspotcode** [comment]
Closing as I don't think there is anything we should change here.  If someone or something modifies `Error.stackTraceLimit`, we can and should respect that setting for the errors that we throw.
