### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by morris** [TypeStrong/ts-node#748]
Hi!

I understand there have been some issues with caching - I recently stumbled on something weird myself when generating coverage with nyc, where the report showed files which didn't exist anymore on disk - and with #701 you've opted to remove caching from ts-node completely in one of the next releases. So a logical thing to do is --no-cache everything until then.

However, this feels next to impractical in terms of performance. I really liked the speed of ts-node with caching and strongly believe it's one of the most important features. Are you planning to fix/reintroduce caching anytime soon? Do you have recommendations on how to continue in the meantime? I was thinking of using a local cache directory in my project(s), and adding a simple cleaning script to remove it whenever problems occur (however, it is hard to determine if something went wrong; any tips appreciated!).

In any case, thanks for maintaining ts-node, probably lots of people relying on it these days :)

**Comment by captain-igloo** [comment]
I opened a caching issue with nyc the other day: https://github.com/istanbuljs/nyc/issues/952 . Your problem could be related to the nyc cache (node_modules/.cache/nyc) or ts-node or both.

**Comment by blakeembrey** [comment]
I'm not planning on re-introducing caching at this time, unless it's entirely fixed which is hard during type-checking mode since you need the entire dependency tree computed. It should be possible though, if someone feels strongly about getting it back. One of the fastest things you can do is use `--transpile-only` mode until someone figured out the dependency caching issues.
