### ISSUE TITLE
Request assistance with nyc to ts-node/register incompatibility

### ISSUE THREAD

**Issue by coreyfarrell** [TypeStrong/ts-node#813]
I'm an nyc maintainer working on istanbuljs/nyc#1002.  I already have a patch in review to address the issue with `coverageData.hash = hash;`.  I have not found a solution for `error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.`.  The instrumented code always contains:
```js
var Function = function () {}.constructor;
var global = new Function("return this")();
```

Worth noting `node -e 'console.log(Function === function() {}.constructor);'` will print true, unfortunately it's possible (in JavaScript) for `Function` to be redefined.  For example the following logs false to the console:
```js
console.log(Function === function () {}.constructor);
function Function() {
  // I don't know why someone would name a function `Function` but it has happened.
}
```

I've tried the following:
```js
var FunctionReplacement = function () {}.constructor;
var globalFinder = Function === FunctionReplacement ? Function : FunctionReplacement;
var global = new globalFinder("return this")();
```
The hope was that in a TypeScript project nobody would have replaced `Function`, so `globalFinder` would be set to `Function`.  ts-node still rejected this code with the same error.  Would it be possible for ts-node/register to understand that `function () {}.constructor === Function`?  I'd like to make it easier to get code coverage for projects using `ts-node/register`, any suggestion would be appreciated.

**Comment by blakeembrey** [comment]
@coreyfarrell Hmm, I've always used `ts-node` to transpile _before_ passing the results to Istanbul. Is my understanding here that you want the wrapper code of Istanbul to be valid TypeScript correct? Can you detect if you're in TypeScript? Not that you probably want to do so, but I'm looking at the TypeScript types and they're pretty non-helpful for this use-case. Since the `Function` type used for the constructor is not the same as the `FunctionConstructor` type declare as the global `Function`. 

The workarounds I see are:

1. Improve TypeScript types for `function () {}.constructor` properties
2. Find a way to write this with good inferred types
3. Remove usage of `.constructor` since it returns the wrong type and rely on `Function` directly

I'll keep thinking a little on 2, but nothing comes to mind right now as a workaround with annotating it explicitly with TypeScript types.

**Comment by coreyfarrell** [comment]
I want the wrapper code to be tolerated as TypeScript, it does need to be valid JavaScript though (this is first priority).  I think the idea behind instrumenting the TypeScript before transpiling it is to avoid generated branches.  I'm unsure what you mean about `Function` vs `FunctionConstructor` since `function () {}.constructor` is the same exact value as the global `Function`.  Is this a situation where the same value has a different type depending on where you get it from?  Would it be possible to unify the types since they are the same thing?

I'm not sure about detecting that we're in TypeScript.  Maybe we could omit the `var Function = function () {}.constructor;` if the source has a `ts` extension.  I'm not sure how else we would detect this?

**Comment by blakeembrey** [comment]
> Is this a situation where the same value has a different type depending on where you get it from?

Yes.

> Would it be possible to unify the types since they are the same thing?

Probably, that would be point 1. You'd need to submit an issue to TypeScript though.

**Comment by blakeembrey** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/3841.

**Comment by coreyfarrell** [comment]
I found the best immediate solution.  We inject the coverage from a babel callback `visitor.Program.exit`, I added a check for `path.scope.getBinding('Function')`.  This way we can output `var Function = function () {}.constructor;` only if the global `Function` was replaced, otherwise we use the built in.  If someone replaces `Function` in TypeScript that's probably an error anyways.

Thanks for helping me understand this and linking me to the TypeScript issue.
