### ISSUE TITLE
@svgdotjs/svg.filter.js dep fails to resolve

### ISSUE THREAD

**Issue by Lange** [TypeStrong/ts-node#870]
I've no idea why, but this one dep just fails to resolve when using `ts-node`. It might be because I currently have to install it as a `github:` dep, due to some bugs fixed in `master` but not yet published as a new release to public npm registry.

I've created a minimal repro and written up more info here: https://github.com/Lange/ts-node-svg-filter-js

**Comment by blakeembrey** [comment]
@Lange Are you seeing this error:

```
Error: Cannot find module '/Users/blakeembrey/Projects/tmp/ts-node-svg-filter-js/node_modules/@svgdotjs/svg.filter.js/dist/svg.filter.node.js'. Please verify that the package.json has a valid "main" entry
```

It's actually by the node.js runtime and it's because there's a build step to get the `dist/` directory created that doesn't exist on GitHub (reference: https://github.com/svgdotjs/svg.filter.js/blob/master/package.json#L54). If they used a `prepare` script instead of `prepublishOnly`, I believe this may be resolved because it runs after an `npm install` also.

**Comment by Lange** [comment]
@blakeembrey that makes sense, I'm guessing it'll be fixed once I get back to using the normal npm releases. I'll close this for now.
