### ISSUE TITLE
`ts-node` won't register itself within node execution context when being launched from NPM's global package folder.

### ISSUE THREAD

**Issue by lu4** [TypeStrong/ts-node#874]
**Long story short** I'm trying to use `ts-node` as an execution environment for my global NPM package. Basically `ts-node` refuses to "register" itself within node execution context when the code located in NPM's global packages folder. I.e. given that I've installed the package using  `npm i -g hcitool-reader` and to launch the package I use one of the following commands:
- `ts-node`
- `node --require ts-node/register`
- or from node.js code `require('ts-node').register({ ... Here I've tried nearly all possible options ... })`

I always get the same result, ts-node suddenly stops understanding typescript and throws bunch of exceptions telling that it doesn't understand typescript.

However if I install the package through `npm i -g /path/to/hcitool-reader/github/repository/on/a/local/disk`

Everything works smoothly. I've tried nearly every possible option with nearly every possible input, as soon as the package gets into NPM's global package folder (no difference how, by manually copying it to NPM's global packages folder or by downloading published NPM package into same NPM's global packages folder) it suddenly stops working. 

**Longer version:**
I'm trying to create a CLI tool that parses output of `hcitool` (a bluetooth utility that reports on various bluetooth stats). The package is called `hcitool-reader` and it can be found [here on NPM](https://www.npmjs.com/package/hcitool-reader) and [here on Github](https://github.com/lu4/hcitool-reader). The application acts similarly to a test runner which dynamically loads files from tests folder, however instead of tests it loads commands that will be available with the application (dynamically). This is why I don't care about performance of the tool right now I would just like to execute ".ts" files on the fly without introducing additional build step for my package. And for this purpose `ts-node` is a great fit (if it would worked with my use-case). 

What am I doing wrong, why ts-node doesn't work from NPM's global packages folder?

Thank you in advance!

**Comment by Lange** [comment]
This is caused by https://github.com/TypeStrong/ts-node/blob/629525474fb548fddb7a90a48ab795a9199b1997/src/index.ts#L207-L209.

This block causes `ts-node` to ignore any file which has `node_modules` in its path. As a temporary fix, try setting a value for `ignore` which will override this. Here's an example I used to ignore all of `node_modules` _except_ my particular folder, using negative lookahead:

```js
require('ts-node').register({
	project: path.resolve(__dirname, '../tsconfig.json'),
	ignore: [
		'node_modules/(?!@tipofthehats)'
	]
});
```

**Comment by blakeembrey** [comment]
@lu4 You can use the `ignore` or `skipIgnore` configurations mentioned by @Lange. By default this module will not compile any files within `node_modules` because that would likely break a lot of applications. For example, if you are using `allowJs` this would have every single file attempt to be compiled by TypeScript that's required - and internally, TypeScript won't compile files it believes are within modules so you'll run into compilation errors quickly. The best workaround is by whitelisting your specific files needed in `ignore`.

**Comment by blakeembrey** [comment]
One possibility is that this configuration could be made cleaner by having a configuration of `include` instead of ignore. In these cases you could specifically do something like `include: ['./**', '!node_modules/**']`, while the default is `!node_modules/**`. Would this make it easier at all?
