### ISSUE TITLE
TypeScript 3.7 Support

### ISSUE THREAD

**Issue by lukeshiru** [TypeStrong/ts-node#903]
I have TypeScript 3.7 installed on a project, and I run tests with ava and ts-node. The issue I found is that compilation works as expected, but tests fail because ts-node doesn't recognize the syntax for nullish coalescence and optional chaining.

So if I have:
```typescript
foobar?.foo?.bar ?? "default value"
```

I get errors all over the place. Isn't `ts-node` using the local typescript package to do compilation?

**Comment by keesvanlierop** [comment]
It does, but it is set to 3.6.4 still. Needs to be updated and then good to go I think?

**Comment by blakeembrey** [comment]
TypeScript 3.7 is already supported, you would need to update your local installation.

**Comment by keesvanlierop** [comment]
It's not supported though. As OP mentions, you'll see errors on optional chaining and nullish coalescing expressinons when running ts-node.

**Comment by lukeshiru** [comment]
One of the errors I'm getting:
```
Uncaught exception in src/tryCatch/tryCatch.test.ts

  ./node_modules/ts-node/src/index.ts:493

  ./src/tryCatch/tryCatch.ts:16
          returnedValue = catchCallback?.(error);
                                        ^

  SyntaxError: Unexpected token '.'

  Module.m._compile (node_modules/ts-node/src/index.ts:493:23)
  module.exports (node_modules/default-require-extensions/js.js:7:9)
  require.extensions.<computed> (node_modules/ts-node/src/index.ts:496:12)
```
Tried a clean install with `npm`, still getting errors.

**Comment by keesvanlierop** [comment]
I noticed the fix is to change `"target": "esnext"` to `"target": "es2018"`. No change required here.

**Comment by blakeembrey** [comment]
By that error it is clearly workin, as you noted it’s failing because you’re compiling an output that node.js doesn’t understand yet.

**Comment by lukeshiru** [comment]
Ohhhh yup. It seems to be a target issue. Thanks @keesvanlierop 😄

**Comment by iwasaki-kenta** [comment]
Is there any way to have nullish coalescing work on target `esnext`? The use case is that bigint's are only supported should `esnext` be targeted, rather than `es2018`.

**Comment by lukeshiru** [comment]
@iwasaki-kenta my solution was to set target to es2018 and then: 
```json
"lib": [
      "es2018",
      "esnext.bigint"
    ]
```
So I have 2018 stuff, but I still support BigInt. It will only work expressed as `BigInt("1")` not like `1n` 😞

**Comment by MikeMitterer** [comment]
OMG I had this same problem with a rollup / Vue / TypeScript combination.
`"target": "es2018"` solved it!

**Comment by ayZagen** [comment]
I am experiencing this issue after upgrading ts `3.7.5` to `3.8.2`. I have tried the solutions above but none of them worked so far. Also tried different es targets with no luck.

**Comment by aqumus** [comment]
For me `"target": "es2019"` and `"target": "es2020"` both works

**Comment by NicoCevallos** [comment]
I faced the same issue but the solution depends of the NodeJS version that runs the script.
With NodeJS 12, it worked with `"target": "ES2018"` and `"target": "ES2019"`, but doesn't work with `"target": "ES2020"`.
But I switched to NodeJS 14 and `"target": "ES2020"` worked fine.
So pay attention to the NodeJS version you are running your scripts

**Comment by alexmacarthur** [comment]
I can also confirm that setting my `target` to `ES2020` didn't work, but `ES2019` _did_ do the trick. I'm running Node v10.15.3.

**Comment by archywillhe** [comment]
this is going backwards it is werid.

**Comment by cspotcode** [comment]
Remember that TypeScript is compiling your code from `.ts` into `.js`, *not* `ts-node`.  We simply use the compiler API, and the returned code is executed by `node`.  What does your node version do when it executes the code being emitted from TypeScript?  What kind of code is being emitted based on your compiler configuration?

If you set `"target": "esnext"`, what code is TypeScript emitting?  What does your node version do when it tries to execute this code?

Make sure you know the answers to these question.  Otherwise, you're likely to confuse yourself and be unsure whether a problem is caused by your configuration or by `ts-node`.  This will waste time and is probably not what you want.

**Comment by jsonchou** [comment]
``` js
nullish coalescing and optional chaining are supported in node >= v14.0.0
```

**Comment by kierans** [comment]
Just to make things a bit easier for new players, remember that ["The target setting changes which JS features are **downleveled**"](https://www.typescriptlang.org/tsconfig#target), that is if the feature isn't natively supported by the NodeJS runtime version the TS compiler generates different code that will run on the node version. That's why `es2020` works on [node >= 14](https://node.green/#ES2020-features-optional-chaining-operator-----) but doesn't on node < 14

**Comment by zWingz** [comment]
Also "target": "es2019" works for me but "target": "es2020" not yet.

**Comment by jedwards1211** [comment]
I think `@babel/preset-env` was pretty wise to support `targets: { node: 'current' }`.  Too bad that `tsconfig.json` doesn't!

**Comment by Thinking80s** [comment]
> I noticed the fix is to change `"target": "esnext"` to `"target": "es2018"` in your tsconfig. No change required here.

why config to `"target": "es2018"` is ok?
