### ISSUE TITLE
Unable to require .ts nested within a node_modules directory

### ISSUE THREAD

**Issue by underflow00** [TypeStrong/ts-node#956]
### Expected Behavior
No errors.

### Actual Behavior
"Unable to require file" error.

### Steps to reproduce the problem
1. Create a package (e.g. using `npm pack`) with the following files:
- `npm-postinstall.ts`:
```
console.log('hello');
import * as x from './x';
console.log('hello2', typeof x);
```

- `package.json`:
```
{
  "name": "package1",
  "version": "0.0.0",
  "scripts": {
    "postinstall": "ts-node --skip-ignore npm-postinstall"
  },
  "dependencies": {
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  }
}
```

- `x.ts`:
```
export const x = 1;
```

2. Install that package: `npm install package1-0.0.0.tgz`

Works fine on Windows

### Specifications

* ts-node version: 8.6.2
* node version: 12.15.0
* Operating system and version: Ubuntu
* If Windows, are you using WSL or WSL2?:

**Comment by underflow00** [comment]
Not a `ts-node` issue apparently. See https://github.com/microsoft/TypeScript/issues/12358. Workaround is to use `--transpile-only`.

**Comment by cspotcode** [comment]
@underflow00 
Thanks for reporting.  I think I have an easy workaround for you, at the bottom of this comment.  Pass `--files` instead of `--skip-ignores`.

If I understand correctly, the TypeScript compiler refuses to compile anything inside a `node_modules` directory unless included via `"includes"` or `"files"` arrays.  When these arrays are omitted, it includes everything in the working directory excluding nested `node_modules`.

You can workaround this limitation by passing `--files` to ts-node.  This prevents `ts-node` from passing empty `"files"` and `"include"` arrays.  When we don't pass any value for those arrays, the compiler defaults to including everything in the working directory.  You don't even need a tsconfig file for this: it will include `npm-postinstall.ts` and `x.ts` by default, and your postinstall script will work.

```
  "scripts": {
    "postinstall": "ts-node --files npm-postinstall"
  },
```

**Comment by cspotcode** [comment]
I'm reopening this because I think it might be a ts-node problem, or at least something that we can fix on our end.

Based on the issue linked here (https://github.com/TypeStrong/ts-node/issues/956#issuecomment-583901995) it sounds like we can implement the host API's `resolveModuleNames` to tell TypeScript if files are considered "external."  I'm guessing the default compiler behavior is to check if we're inside a node_modules directory.  But for us, it seems smarter to check only for node_modules directories that are either nested within our `project` directory or entirely outside of `project`.

For example, if `project` is `/project/node_modules/module1`, we should compile / not compile the following files:

```
/project/node_modules/module1/foo.ts -> YES, compile
/project/node_modules/module1/bar.ts -> YES, compile
/project/node_modules/module1/node_modules/other/src/index.ts -> NO, do not compile
/project/node_modules/other/src/index.ts -> NO, do not compile
```

**Comment by cspotcode** [comment]
Linking to a related TypeScript issue: https://github.com/microsoft/TypeScript/issues/28432#issuecomment-437498123

The behavior described in that comment matches what I described in my previous comment.
