### ISSUE TITLE
Random Error with TypeScript 3.8.2

### ISSUE THREAD

**Issue by donle** [TypeStrong/ts-node#979]
* Cannot read syntax `import type`

 * Random runtime error when importing a `const enum`. The enum value imported sometimes randomly becomes another value from the enum when running with ts-node. Running the code after compiled to javascript is all good. this happens since I upgraded TypeScript from 3.7.5 to 3.8.2.

*~Bugs from mac, gonna attempt to reproduce bugs on Windows later~, can't reproduce on Windows, only happens on mac (and maybe linux)*

**Comment by blakeembrey** [comment]
@donle What's the error for 1? It sounds a little like TypeScript is not updated or registered properly.

**Comment by donle** [comment]
> @donle What's the error for 1? It sounds a little like TypeScript is not updated or registered properly.

> return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:

Didn't have any register issues before upgrading to ts 3.8.x

**Comment by blakeembrey** [comment]
@donle Are you sure you're running 3.8? You can check with `ts-node -vv`. That kind of looks like you're using new syntax without the correct TypeScript version.

**Comment by blakeembrey** [comment]
However, you should be getting this error on Windows and Linux consistently so that's concerning.

**Comment by cspotcode** [comment]
These look like exactly the errors that happen when you're using an older version of TypeScript.

Here is a reproduction using TypeScript 3.7.5.  Since you attempted to reproduce on multiple operating systems, it's likely that one system had a different version of TypeScript installed.

[Playground Link](https://www.typescriptlang.org/play?ts=3.7.5#code/JYWwDg9gTgLgBDAnmApnA3nASighgGwGFcoATASVLgF84AzKCEOAcgGNoUB6Nk0gZy75gAI0G8yAfTCMw-FgG4gA)

**Comment by cspotcode** [comment]
Closing as answered.
