### ISSUE TITLE
Priting to Stdout

### ISSUE THREAD

**Issue by Burtannia** [TypeStrong/ts-node#982]
I'm currently trying to find a way to read from stdin, compile with `tsc` and output to stdout. It seems possible to tell `tsc` to output to stdout via `--out /dev/stdout` however I can't seem to find a way to get `tsc` to read from stdin.

While searching for solutions I came across `ts-node` for which I seem to have the inverse problem. I can read from stdin but can't figure out how to send the compiled output to stdout. I tried passing `--out /dev/stdout` to the compiler via the `-O` flag mentioned in the README but either it doesn't work or I couldn't get the formatting right.

Is this possible with `ts-node`? If not then is there any other direction someone could point me in that might be helpful?

Thanks.

**Comment by blakeembrey** [comment]
The output you want is compiled TypeScript code right? That's not a part of this package, since this executes the code. You'd have to write some JavaScript to do that. It's relatively easy depending on what you want to to do exactly (e.g. `tsconfig.json` file support? just transpile?), you'd just need to read from `process.stdin` and write back to `process.stdout`. Your best places are the TypeScript documentation for how to use the compiler, and the node.js documentation. If it helps, check `src/{bin,index}.ts` which does some of this.

**Comment by Burtannia** [comment]
@blakeembrey Thanks for the response. I do indeed want compiled TypeScript code as the output. My biggest problem is that, after reviewing the TS documentation, I can't seem to find a way to invoke the TS compiler on input that isn't in a file.

**Comment by blakeembrey** [comment]
https://github.com/TypeStrong/ts-node/blob/e8df418a3e811ae41e39bb73104711c6228c6262/src/bin.ts#L234
