### ISSUE TITLE
Readme.md: require.extensions is deprecated

### ISSUE THREAD

**Issue by dilyanpalauzov** [TypeStrong/ts-node#989]
Readme.md talks twice about `require.extensions`, but per https://nodejs.org/api/modules.html#modules_require_extensions this is deprecated.  Please rewrite the file, reflecting the deprecated status

**Comment by cspotcode** [comment]
See past discussion: #641

Despite being deprecated for about 5 years, this feature continues to be used reliably by many tools.  Coffeescript and babel both have similar loaders.  Tools that support config files written in non-js languages use something similar, for example, via rechoir.

I checked the docs for @babel/node, @babel/register, and coffeescript.  None of them mention that `require.extensions` is deprecated.  I assume this is because mentioning it is confusing and wrongly suggests that the feature will be disappearing soon.  Per #641, there are no alternatives, and it works reliably.

**Comment by dilyanpalauzov** [comment]
Moved to https://github.com/nodejs/node/issues/32483.
